### ISSUE TITLE
Cannot render list of strings Argument.

### ISSUE THREAD

**Issue by mmx86** [denisart/graphql-query#10]
Hi! Nice library. I'm willing to use it in my project. But I have an issue:
```
input SomeInput {
    someListArgument: [String!]!
}
```
Given list of strings, I'd like to generate string `someListArgument: ["value"]`.
The following raises pydantic validation error:
```
graphql_query.Argument(name='someArgument', value=['value'])
```
```
E   pydantic.error_wrappers.ValidationError: 5 validation errors for Argument
E   value
E     str type expected (type=type_error.str)
E   value
E     value is not a valid dict (type=type_error.dict)
E   value -> 0
E     value is not a valid dict (type=type_error.dict)
E   value -> 0
E     value is not a valid list (type=type_error.list)
E   value
E     value is not a valid dict (type=type_error.dict)
```
And this  generates object instead of array:
```
graphql_query.Argument(name='someArgument', value=[
    graphql_query.Argument(name='someArgumentItem', value=v)
    for v in ['value']
])
```
There doesn't seem to be a nice way to generate an array argument. (I have to explicitly render it as string right now)
I havent tried variables. But even if they work, I'd like to keep my query explicit. 

Thanks in advance!

**Comment by denisart** [comment]
hello, thanks for your question!

Yes, it is problem now. We can not use an argument value with list of strings.

There will be a new version soon that includes a fix for this issue.
