### ISSUE TITLE
Quotes are stripped from list of strings in Argument

### ISSUE THREAD

**Issue by NT-Timm** [denisart/graphql-query#21]
**To Reproduce**
`print(Argument(name='someArgument', value=['value']).render())`
`someArgument: [value]`
`print(Argument(name='someArgument', value=["value"]).render())`
`someArgument: [value]`

**Expected behavior**
`print(Argument(name='someArgument', value=['value']).render())`
`someArgument: ['value']`
`print(Argument(name='someArgument', value=["value"]).render())`
`someArgument: ["value"]`

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Python 3.10

It would suck having to write code to manually double quote lists of strings.

**Comment by denisart** [comment]
Hello, thanks for the question.

You are right, the current result is not correct.
I will fix this problem soon. After pydantic version 2 support.

**Comment by NT-Timm** [comment]
I found another "question"
It seems python bools are not supported as well. 
They turn into the standard str from python. (which is either True or False) 
While graphql only accepts true or false.

**Comment by denisart** [comment]
@NT-Timm , hello
last release (https://github.com/denisart/graphql-query/releases/tag/v1.2.0) supported `bool` and `List[bool]`. And based on pydantic v2.

Later I will think about your original question.
